   Importance of Numpy
1. Allows Several Mathmetical operations
2. Faster Operations  

In [1]:
import numpy as np
from time import process_time 

 List vs Numpy

In [2]:
first_list=[];
second_list=[];
for i in range(10000000):
    first_list.append(i+1);

start_time=process_time();


for i in range(10000000):
    second_list.append(first_list[i] + 5);

end_time=process_time();

print(end_time - start_time)

3.453125


In [3]:
np_array=np.array([i for i in range(10000000)])
start_time=process_time();
np_array +=5;
end_time=process_time();
print(end_time - start_time)

0.0


Dimentional Array 

In [4]:
nd_array=np.array([1,2,3,4])
print('1d array :',nd_array)

nd_array=np.array([(1,2,3,4),(1,2,3,4)])
print('2d array :',nd_array)

nd_array=np.array([(1,2,3,4),(1,2,3,4),(1,2,3,4)], dtype=float)
print('3d array :',nd_array)

1d array : [1 2 3 4]
2d array : [[1 2 3 4]
 [1 2 3 4]]
3d array : [[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Finding Shape


In [5]:
shape=nd_array.shape
print(shape)

(3, 4)


Initial Palaceholder in Numpy Array

In [6]:
zeros_array=np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
ones_array=np.ones((3,3))
print(ones_array)



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
full=np.full((3,3),5,dtype=float)
print(full)



[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [9]:
making_array_from_random=np.random.random((3,4))
print(making_array_from_random)

[[0.19483581 0.09972264 0.58439178 0.10981847]
 [0.32145249 0.63717694 0.52745245 0.08575912]
 [0.53862005 0.06363057 0.94883253 0.17889332]]


In [ ]:
making_array_from_random_with_intiger_value=np.random.randint(10,100,(100,10))
print(making_array_from_random_with_intiger_value)

In [11]:
eye=np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Array With Evenly Space Value

In [14]:
spaceValue=np.linspace(10,100,5,dtype=int)
print(spaceValue)

[ 10  32  55  77 100]


Array With Specifing the Step


In [19]:
spaceValue=np.arange(10,100,10)
print(spaceValue)

[10 20 30 40 50 60 70 80 90]


List to Numpy


In [21]:
list=[1,2,3,4,5,6,78,'english']
my_np_array=np.array(list)
print(my_np_array)

['1' '2' '3' '4' '5' '6' '78' 'english']


Numpy Array Analysis

In [23]:
randomArray=np.random.randint(10,100,(10,10))
print(randomArray)

[[97 73 98 17 33 68 38 85 63 20]
 [96 96 32 62 76 63 90 97 82 25]
 [25 38 56 54 93 74 35 53 60 53]
 [24 33 16 84 33 58 63 49 36 95]
 [62 80 90 47 82 93 27 80 57 11]
 [10 71 53 22 27 82 43 43 57 83]
 [40 85 65 21 80 53 34 31 84 57]
 [47 55 13 33 71 11 75 33 57 18]
 [15 44 79 78 88 21 74 64 45 51]
 [32 55 88 19 64 82 72 53 75 42]]


In [24]:
print('dimention :',randomArray.shape)

dimention : (10, 10)


In [25]:
print('size :',randomArray.size)

size : 100


In [26]:
print('ndim',randomArray.ndim)

ndim 2


In [27]:
print('type :',type(randomArray))

type : <class 'numpy.ndarray'>


In [28]:
print('type :',randomArray.dtype)

type : int32


In [31]:
list=np.random.randint(1,10,(4,8))
print(list)
reshape=list.reshape(8,4)
print(reshape)

[[7 3 3 7 9 3 4 6]
 [3 4 4 2 9 6 4 2]
 [6 7 3 3 5 2 2 2]
 [4 9 7 9 9 4 4 4]]
[[7 3 3 7]
 [9 3 4 6]
 [3 4 4 2]
 [9 6 4 2]
 [6 7 3 3]
 [5 2 2 2]
 [4 9 7 9]
 [9 4 4 4]]


In [32]:
list=list=np.random.randint(1,10,(2,3))
print(list)
transpose=np.transpose(list)
print(transpose)

[[4 6 6]
 [4 7 9]]
[[4 4]
 [6 7]
 [6 9]]


Mathmatical Operations


In [37]:
a=np.random.randint(1,10,((3,3)))
print('a :',a)
b=np.random.randint(1,10,((3,3)))
print('b :',b)

a : [[2 3 8]
 [2 5 3]
 [9 2 8]]
b : [[3 3 7]
 [1 5 4]
 [8 6 1]]


In [41]:
print('a+b :\n',np.add(a,b),'\n')
print('a-b :\n',np.subtract(a,b),'\n')
print('a*b :\n',np.multiply(a,b),'\n')
print('a/b :\n',np.divide(a,b),'\n')

a+b :
 [[ 5  6 15]
 [ 3 10  7]
 [17  8  9]] 

a-b :
 [[-1  0  1]
 [ 1  0 -1]
 [ 1 -4  7]] 

a*b :
 [[ 6  9 56]
 [ 2 25 12]
 [72 12  8]] 

a/b :
 [[0.66666667 1.         1.14285714]
 [2.         1.         0.75      ]
 [1.125      0.33333333 8.        ]] 

