In [7]:
import numpy as np
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data
print(np.append(data,[4,5,3]))

[1 2 3 4 5 6 7 8 9 4 5 3]


In [10]:
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data
print(np.insert(data,0,[4,5,3],axis=1))

[[4 1 2 3]
 [5 4 5 6]
 [3 7 8 9]]


In [12]:
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
data
print(np.delete(data,1,axis=1))

[[1 3]
 [4 6]
 [7 9]]
