In [17]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[11,12,13],[14,15,16],[17,18,19]]
a=np.array(a)
b=np.array(b)
print('concatenate',np.concatenate([a,b],axis=0))




print("............split.............")
c=np.array_split(a,2)
for i in range(len(c)):
    print(c[i])

concatenate [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
............split.............
[[1 2 3]
 [4 5 6]]
[[7 8 9]]
