In [21]:
import numpy as np
data=[[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]]
data=np.array(data)
data.ndim
print(data[0:4,1:4])
print("\n")
print(data[2,2:])

[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]]


[15 16 17 18]
