In [6]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=[[11,12,13],[14,15,16],[17,18,19]]
a=np.array(a)
b=np.array(b)
print(a+b)
print(np.add(a,b))
print(".....................................................")
print(a-b)
print(np.subtract(a,b))
print(".....................................................")
print(a*b)
print(np.multiply(a,b))
print(".....................................................")
print(a/b)
print(np.divide(a,b))
print(".....................................................")
print(np.transpose(a))


[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[12 14 16]
 [18 20 22]
 [24 26 28]]
.....................................................
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
.....................................................
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
.....................................................
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]
.....................................................
[[1 4 7]
 [2 5 8]
 [3 6 9]]
